version: "3.3"
services:
  mysql:
    image: mysql:5.7 
    environment:
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
        - MYSQL_ROOT_PASSWORD=testroot
    ports:
      - "33060:3306"
    volumes:
      - ./create_dbs.sql:/docker-entrypoint-initdb.d/init.sql #  creates main DB and test DB