package com.tqs108636;

// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

import io.github.bonigarcia.seljup.BrowserType;
import io.github.bonigarcia.seljup.DockerBrowser;
import io.github.bonigarcia.seljup.SeleniumJupiter;

import com.tqs108636.pages.ChooseFlightPage;
import com.tqs108636.pages.ConfirmationPage;
import com.tqs108636.pages.HomePage;
import com.tqs108636.pages.PurchaseFlightPage;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;

@ExtendWith(SeleniumJupiter.class)
public class BlazeBrowsersTest {
    JavascriptExecutor js;

    @Test
    void testChrome(@DockerBrowser(type = BrowserType.CHROME) WebDriver driver) {
        testBlazeWithDriver(driver);
    }

    @Test
    void testOpera(@DockerBrowser(type = BrowserType.OPERA) WebDriver driver) {
        testBlazeWithDriver(driver);
    }

    @Test
    void testFirefox(@DockerBrowser(type = BrowserType.FIREFOX) WebDriver driver) {
        testBlazeWithDriver(driver);
    }

    @Test
    void testEdge(@DockerBrowser(type = BrowserType.EDGE) WebDriver driver) {
        testBlazeWithDriver(driver);
    }

    // Runs test with given WebDriver
    public void testBlazeWithDriver(WebDriver driver) {
        HomePage homePage = new HomePage(driver);
        homePage.selectMexicoCity();
        ChooseFlightPage chooseFlightPage = homePage.clickFindFlights();
        // assert h3 to say Mexico City to Buenos Aires based on previous click
        assertThat(chooseFlightPage.getH3Heading(), equalTo("Flights from Mexico City to Buenos Aires:"));
        // assert title
        assertThat(chooseFlightPage.getTitle(), equalTo("BlazeDemo - reserve"));
        PurchaseFlightPage purchaseFlightPage = chooseFlightPage.clickChooseFlightButton();

        assertThat(purchaseFlightPage.getTitle(), equalTo("BlazeDemo Purchase"));
        assertThat(purchaseFlightPage.getH2Heading(), equalTo("Your flight from TLV to SFO has been reserved."));
        purchaseFlightPage.name("Test1");
        purchaseFlightPage.address("Test2");
        purchaseFlightPage.city("Test3");
        purchaseFlightPage.state("Test4");
        purchaseFlightPage.zipCode("Test5");
        purchaseFlightPage.creditCardNumber("Test6");
        purchaseFlightPage.nameOnCard("Test7");
        ConfirmationPage confirmationPage = purchaseFlightPage.clickPurchaseFlight();

        assertThat(confirmationPage.getTitle(), equalTo("BlazeDemo Confirmation"));
        assertThat(confirmationPage.getH1Heading(), equalTo("Thank you for your purchase today!"));
    }
}